FRONTEND:
  URL: "http://localhost:3000"
JWT:
  EXPIRE : 2000
DATABASE:
  PORT: "5432"
  USER: "admin"
DBNAME:
  AUTH: "auth"
  BOOKS : "books"
  REVIEWS : "reviews"
  PAYMENTS : "payments"
  LENDING : "lending"
PORT:
  API: 3460
  AUTH: 3475
  PAYMENTS: 3480
  ADMIN:
    BOOKS : 3700
    LENDING : 3701
  