basePath: /auth
definitions:
  auth.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  auth.UserSignupRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
    required:
    - email
    - name
    - password
    type: object
info:
  contact: {}
  description: Authentication Server
  title: AuthServer
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a token
      parameters:
      - description: User Login Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses: {}
      summary: User Login
      tags:
      - Auth
  /signup:
    post:
      consumes:
      - application/json
      description: Registers a new user
      parameters:
      - description: User Signup Data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.UserSignupRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
      summary: User Signup
      tags:
      - Auth
swagger: "2.0"
